// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: api/senate/senate.proto

package senate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_role      Role = 0
	Role_leader    Role = 1
	Role_follower  Role = 2
	Role_candidate Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "role",
		1: "leader",
		2: "follower",
		3: "candidate",
	}
	Role_value = map[string]int32{
		"role":      0,
		"leader":    1,
		"follower":  2,
		"candidate": 3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_senate_senate_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_senate_senate_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_senate_senate_proto_rawDescGZIP(), []int{0}
}

type SyncTermReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Role Role   `protobuf:"varint,3,opt,name=role,proto3,enum=senate.v1.Role" json:"role,omitempty"`
	Vote string `protobuf:"bytes,4,opt,name=vote,proto3" json:"vote,omitempty"`
	Term int32  `protobuf:"varint,5,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *SyncTermReq) Reset() {
	*x = SyncTermReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_senate_senate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncTermReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTermReq) ProtoMessage() {}

func (x *SyncTermReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_senate_senate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTermReq.ProtoReflect.Descriptor instead.
func (*SyncTermReq) Descriptor() ([]byte, []int) {
	return file_api_senate_senate_proto_rawDescGZIP(), []int{0}
}

func (x *SyncTermReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SyncTermReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncTermReq) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_role
}

func (x *SyncTermReq) GetVote() string {
	if x != nil {
		return x.Vote
	}
	return ""
}

func (x *SyncTermReq) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type SyncTermResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready bool   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Vote  string `protobuf:"bytes,2,opt,name=vote,proto3" json:"vote,omitempty"`
	Term  int32  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Role  Role   `protobuf:"varint,4,opt,name=role,proto3,enum=senate.v1.Role" json:"role,omitempty"`
}

func (x *SyncTermResp) Reset() {
	*x = SyncTermResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_senate_senate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncTermResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTermResp) ProtoMessage() {}

func (x *SyncTermResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_senate_senate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTermResp.ProtoReflect.Descriptor instead.
func (*SyncTermResp) Descriptor() ([]byte, []int) {
	return file_api_senate_senate_proto_rawDescGZIP(), []int{1}
}

func (x *SyncTermResp) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *SyncTermResp) GetVote() string {
	if x != nil {
		return x.Vote
	}
	return ""
}

func (x *SyncTermResp) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *SyncTermResp) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_role
}

type HeartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderId string `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Term     int32  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *HeartReq) Reset() {
	*x = HeartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_senate_senate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartReq) ProtoMessage() {}

func (x *HeartReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_senate_senate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartReq.ProtoReflect.Descriptor instead.
func (*HeartReq) Descriptor() ([]byte, []int) {
	return file_api_senate_senate_proto_rawDescGZIP(), []int{2}
}

func (x *HeartReq) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *HeartReq) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type HeartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *HeartResp) Reset() {
	*x = HeartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_senate_senate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartResp) ProtoMessage() {}

func (x *HeartResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_senate_senate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartResp.ProtoReflect.Descriptor instead.
func (*HeartResp) Descriptor() ([]byte, []int) {
	return file_api_senate_senate_proto_rawDescGZIP(), []int{3}
}

func (x *HeartResp) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_senate_senate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_api_senate_senate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_api_senate_senate_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_senate_senate_proto protoreflect.FileDescriptor

var file_api_senate_senate_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x6e,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x6e, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7e, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x65, 0x72,
	0x6d, 0x22, 0x71, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12,
	0x23, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x73, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x22, 0x3b, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x65, 0x72,
	0x6d, 0x22, 0x21, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x22, 0x18, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x39,
	0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x10, 0x03, 0x32, 0xb2, 0x01, 0x0a, 0x04, 0x4c, 0x69,
	0x76, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x73, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6f, 0x6e, 0x67, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x73, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x73, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x65,
	0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x6e, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0c,
	0x5a, 0x0a, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_senate_senate_proto_rawDescOnce sync.Once
	file_api_senate_senate_proto_rawDescData = file_api_senate_senate_proto_rawDesc
)

func file_api_senate_senate_proto_rawDescGZIP() []byte {
	file_api_senate_senate_proto_rawDescOnce.Do(func() {
		file_api_senate_senate_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_senate_senate_proto_rawDescData)
	})
	return file_api_senate_senate_proto_rawDescData
}

var file_api_senate_senate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_senate_senate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_senate_senate_proto_goTypes = []interface{}{
	(Role)(0),             // 0: senate.v1.Role
	(*SyncTermReq)(nil),   // 1: senate.v1.SyncTermReq
	(*SyncTermResp)(nil),  // 2: senate.v1.SyncTermResp
	(*HeartReq)(nil),      // 3: senate.v1.HeartReq
	(*HeartResp)(nil),     // 4: senate.v1.HeartResp
	(*Pong)(nil),          // 5: senate.v1.Pong
	(*emptypb.Empty)(nil), // 6: google.protobuf.Empty
}
var file_api_senate_senate_proto_depIdxs = []int32{
	0, // 0: senate.v1.SyncTermReq.role:type_name -> senate.v1.Role
	0, // 1: senate.v1.SyncTermResp.role:type_name -> senate.v1.Role
	6, // 2: senate.v1.Live.Ping:input_type -> google.protobuf.Empty
	1, // 3: senate.v1.Live.CampaignLeader:input_type -> senate.v1.SyncTermReq
	3, // 4: senate.v1.Live.HeartBeat:input_type -> senate.v1.HeartReq
	5, // 5: senate.v1.Live.Ping:output_type -> senate.v1.Pong
	2, // 6: senate.v1.Live.CampaignLeader:output_type -> senate.v1.SyncTermResp
	4, // 7: senate.v1.Live.HeartBeat:output_type -> senate.v1.HeartResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_senate_senate_proto_init() }
func file_api_senate_senate_proto_init() {
	if File_api_senate_senate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_senate_senate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncTermReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_senate_senate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncTermResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_senate_senate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_senate_senate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_senate_senate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_senate_senate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_senate_senate_proto_goTypes,
		DependencyIndexes: file_api_senate_senate_proto_depIdxs,
		EnumInfos:         file_api_senate_senate_proto_enumTypes,
		MessageInfos:      file_api_senate_senate_proto_msgTypes,
	}.Build()
	File_api_senate_senate_proto = out.File
	file_api_senate_senate_proto_rawDesc = nil
	file_api_senate_senate_proto_goTypes = nil
	file_api_senate_senate_proto_depIdxs = nil
}
